package com.airbyte.daneshmal.security.jwt;

public class JwtConfig {
    public static final String SECURE_KEY = "secureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKeysecureKey";
}
